apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: calc
  labels:
    app: calc
    env: main
  namespace: loginapp
spec:
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      name: calc
      labels:
        env: main
        app: calc
    spec:
      
      containers:
      - name: calc
        image: devopsinnroad.jfrog.io/rayudu-builds/calc:df1c758
        imagePullPolicy: Always
        resources:
        ports:
        - containerPort: 80
          name: http
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: loginapp

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/success-codes: 200-499
  name: calc
  namespace: loginapp
  labels:
    Domain: login.qa4innroad.com
spec:
  selector:
    app: calc
    env: main
  ports:
  - port: 80
    name: http
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
